### ISSUE TITLE
Apparently doesn’t work on wasm build

### ISSUE THREAD

**Issue by ValorZard** [taurr/bevy-template-rs#18]
This is a problem since wasm/webgl builds are important for game jams

**Comment by taurr** [comment]
@ValorZard how to reproduce? steps to take?

Assume I know nothing of WASM (which I basically don't)

**Comment by rparrett** [comment]
I think the idea behind this issue is that it would be great to give users a quick way to build their game for the web with this template.

As an example, the [official Bevy template](https://github.com/bevyengine/bevy_github_ci_template) has a "release" workflow that does cross-platform builds, including bundling up a web build into a handy zip file that could be deployed to `itch.io`. (but doesn't help users do development for the web locally, really)

[bevy_game_template](https://github.com/NiklasEi/bevy_game_template) also comes with a workflow for deploying a web build to github pages which is super handy.

The quickest way for bevy users to just run their app in a webserver is via [wasm-server-runner](https://crates.io/crates/wasm-server-runner), which if installed and configured by a user, allowed them to just do `cargo run --target=wasm32-unknown-unknown`. But I'm not really sure how that could be templatized.

I've been using a [cargo make-file](https://github.com/rparrett/taipo/blob/main/Makefile.toml) along with the workflows from `bevy_github_ci_template` but I'm not super crazy about it.

**Comment by taurr** [comment]
@ValorZard @rparrett I've included some WASM configuration support in the binary template.
Also, the workflow template now uses the WF from [the official Bevy workflow template](https://github.com/bevyengine/bevy_github_ci_template).

I believe this should to it - otherwise please feel free to create a new issue, preferable with a bit better explanation :-)

Thanks to rparret for the current clarification.
